# Generated by Django 4.1.5 on 2023-01-22 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField()),
                ('lens_mul', models.SmallIntegerField()),
                ('orth', models.SmallIntegerField()),
                ('pic_num', models.SmallIntegerField()),
                ('mine_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rock.mine')),
            ],
        ),
        migrations.AddField(
            model_name='mine',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rock.region'),
        ),
    ]
