# Generated by Django 4.1.5 on 2023-01-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0002_picinfo_image_picinfo_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picinfo',
            name='orth',
            field=models.CharField(blank=True, choices=[('o', '正交'), ('p', '单偏')], default='o', max_length=1),
        ),
    ]
