# Generated by Django 4.1.5 on 2023-01-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0004_alter_picinfo_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picinfo',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
