# Generated by Django 4.1.5 on 2023-01-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0005_alter_picinfo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/rocks/')),
            ],
        ),
        migrations.AlterField(
            model_name='picinfo',
            name='image',
            field=models.ImageField(upload_to='img/rocks/'),
        ),
    ]
