# Generated by Django 4.1.5 on 2023-01-30 07:30

from django.db import migrations, models
import rock.models


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0007_remove_pic_image_pic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='image',
            field=models.ImageField(default='path/to/my/default/image.jpg', upload_to=rock.models.get_upload_to),
        ),
    ]
