# Generated by Django 4.1.5 on 2023-01-30 07:52

from django.db import migrations, models
import rock.models


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0008_pic_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pic',
        ),
        migrations.AlterField(
            model_name='picinfo',
            name='image',
            field=models.ImageField(upload_to=rock.models.get_upload_to),
        ),
    ]
