# Generated by Django 4.1.7 on 2023-04-07 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0011_rocksamplename_rocksamplestructure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rocksample',
            name='mine_num',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rock.mine'),
            preserve_default=False,
        ),
    ]
