# Generated by Django 4.1.7 on 2023-04-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0012_rocksample_mine_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='rocksample',
            name='method',
            field=models.IntegerField(choices=[(0, '碎屑岩'), (1, '岩浆岩'), (2, '井壁取心')], default=0),
        ),
    ]
